# Generated by Django 4.2 on 2023-04-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_capfootball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='jogoid',
        ),
    ]
