# Generated by Django 4.2 on 2023-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_capfootball', '0004_alter_jogos_data_alter_jogos_dia_alter_jogos_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administradores',
            },
        ),
    ]
