# Generated by Django 4.2 on 2023-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_capfootball', '0005_administradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='data',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
