# Generated by Django 4.2 on 2023-04-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_capfootball', '0006_alter_jogos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='data',
            field=models.DateField(default=None, max_length=15),
        ),
    ]
